### ISSUE TITLE
Proposal - Penalties for invalid submissions

### ISSUE THREAD

**Issue by MiloTruck** [code-423n4/org#127]
## Problem

Currently, there are no penalties for submitting invalid submissions. 

This incentivises wardens to submit issues without caring if they are valid - if a warden is unsure of a finding's validity, from a logical perspective it makes sense to just submit it for a chance of getting a payout. 

Furthermore, this encourages what I call "spray and pray" - wardens just submit whatever they can think of without checking if it's actually valid, hoping it gets duped to a higher quality report or what they submitted just so happens to be valid.

I believe this is  harmful as:
- Judges have to deal with a gazillion low quality findings for every contest.
- It is extremely discouraging for wardens who put in effort to write PoCs or validate their findings, since someone else who simply spammed findings could have gotten the same or even a higher payout.

Therefore, I would like to propose some form of penalty for invalid submissions to disincentivise such behavior.

### Defining "Invalid"

Submissions should only be deemed invalid if they are unsatisfactory [according to the C4 docs](https://docs.code4rena.com/awarding/incentive-model-and-awards#satisfactory-unsatisfactory-submissions).

This does **not** include downgraded findings since they are technically valid, just that the severity was misclassified.

### What other platforms have done

[CodeHawks](https://docs.codehawks.com/judging/disqualification-criteria) implements a per-contest validity threshold of 15%. This means that if over 85% of a participant's submissions in a contest are deemed invalid, they will not get paid.  

- Pros
    - Penalties are on a per-contest basis, so there aren't any lasting impacts for wardens.
- Cons
    - The threshold could be unfair for wardens with a small number of submissions (eg. 1 valid, 6 invalid - 14.2%). 

[Sherlock](https://docs.sherlock.xyz/audits/watsons/meeting-the-payout-criteria#2.-issues-ratio) also maintains a validity threshold of 20%, except that it's a lifetime ratio for a watson's account, calculated as:

```
# of valid issues submitted / total # of issues submitted
```
If a watson's % of valid issues goes below this threshold, they do not receive any payouts until their % goes back up.

- Pros
    - Wardens have more leeway for valid issues in a contest. If a warden consistently has a high % of valid issues for past contests, he will not be penalized even if he happens to have a bad contest.
    - Wardens who have submitted tons of invalid issues in the past will be forced to maintain a high % of valid issues for future contests.
- Cons
    - Payouts are withheld for contests, which can be frustrating for wardens. I also don't believe C4 currently has the infrastructure to support this.
    - Wardens will be incentivised to create new accounts to reset their lifetime ratio.

### My thoughts

In my opinion, having a validity threshold that grows based on a warden's number of issues submitted per-contest is a good idea. 

For example, assume `x` is the number of submissions a warden has for a contest:
- `x < 7` - No penalty
- `7 <= x < 12` - threshold = 15%
- `12 <= x < 20` - threshold = 20%
- `x >= 20` - threshold = 30%

There could even be some sort of exponential formula for this, where if `x` approaches 100, the threshold would grow exponentially to 90%.

This could also be beneficial for judging - once a warden's number of invalid submissions has crossed the validity threshold, all their submissions can be marked as invalid. However, there is a risk of  valid solo findings being missed and not raised to the sponsor.

## Other remarks

I'm interested in hearing feedback/thoughts from wardens, lookouts/judges and possibly C4 staff on this.

Penalties can be a very delicate subject; if overly aggressive, they could unintentionally discourage wardens from submitting real vulnerabilities.

Thank you for coming to my TED talk.

**Comment by xuwinnie** [comment]
This idea seems interesting. Instead of invalidating all issues as a penalty, how about we implement a 'review fee', maybe $100 per issue? If more than 50% of a warden's findings are incorrect, we deduct the fee from their reward. This might better reflect the cost of spamming and if a spam guy really finds a rare issue, the penalty is not that servere. Would like to hear everyone's feedback.

**Comment by Frankcastleauditor** [comment]
I think that the formula of calculating the validitiy threshold should also depend on the size of the protocol ( sloc of each protocol ) 
Since the validity threshold to be set to zero if the submited issues are less that 7 should not be equal for two protocols , one has100 sloc ( as we saw the canto liquidity minting contract with 80 sloc ) and one has 10000 sloc because the ratio of issues per line  will be ; 
1) 0.07 issue per the line of the first protocol, which means about one issue per 15 lines . 
2) 0.00007 issue per the line of the second, which means about one issue per 1430 lines . 
So, the possibility of spaming all the possible findings in the first one is so big , and the restriction of the second big protocol is so high also because as you know the more big is the protocol the more issues will be valid . 
, so I believe that the formula of the threshold should include the number of lines of the protocol as a parameter to calculate the validity threshold .

**Comment by GalloDaSballo** [comment]
I believe that clear spammers should be manually banned, if your behaviour is so despicable that the judge wants to go out of their way to ensure your findings are closed, no reward should be awarded

Behaviour like this will force C4 to put a Fee to compete long term, and for these reasons I have nothing but contempt

**Comment by sockdrawermoney** [comment]
Reposting my comment here in discord.

We have come to the conclusion that both penalties and charging a fee to submit are incomplete solutions for a variety of reasons.

We have something in the works which should address this. It’s just gotten blocked by other things we’re working on shipping.

To your comment, @GalloDaSballo, I'd have no qualms with officially saying we dead-end accounts that a judge deems is submitting spam. Might be ideal to require a +1 from another judge in formalizing that.

**Comment by zhaojio** [comment]
There are too many invalid reports, which is really a big problem, and it is unfair for people who are committed to submitting effective reports, because effective reports are drowned out, judges are more inclined to close reports, and effective reports are easily misjudged and then closed.

I think people should be encouraged to submit valid reports, not punished, and if a person submits a report that is 100% valid then he should receive an additional reward, just as if the report was selected as report. However, the calculation method also needs to consider some issues, such as someone who has multiple accounts and only submits one report at a time.

**Comment by abarbatei** [comment]
> In my opinion, having a validity threshold that grows based on a warden's number of issues submitted per-contest is a good idea.

Touching on the idea of penalties and threshold (and since I am a numbers lover) I think calculating a validity score for warden would be good either-way and like @MiloTruck indicated have not penalties, but limitations. For example, a simple one:
- if warden validity score < 30% have him require a coded POC or automatically dismiss his finding (Lookout would need to determine if a Coded POC can exist, and if not, a written POC, and if not, the issue can be dismissed without nobody reading it).

Only this "limitation" is something that can benefit almost everybody. I think we can still brainstorm in this direction, of "threshold required limitations that work to benefit others".

An example, 0x52 is known for mostly not writing coded POCs (I have not seen even one, but didn't check them all) but he is reputable and a written/theoretical POC suffices from him. Someone that is know to spam invalid issues would statistically chose written POCs because they are easier. No, don't allow him because he has shown that his findings are not that valid. This limitation of course allows one to grow, since it's threshold dependent and would be lifted the more he proves himself.

**Comment by abarbatei** [comment]
Another thing we can do, focusing on incentives is regarding best report. Right now, best report gets 30% extra payment.
I would suggest expanding on this: say increase payment to 50% and distribute that 50% like QAs, by scoring each report and giving a percentage of that 50% to each report that is scored. The best still gets to be the one selected for report and may even gain better then the initial 30%. 

You can also make it a requirement that only issues with POCs (where there can be, Lookout/judge decides) can be eligible for this bonus.

**Comment by KnownFactC4** [comment]
Per the Autumn 2023 C4 Supreme Court verdicts, the Supreme Court's verdict on this issue is: 

** > Per-invalid penalties shall not be imposed on wardens. However, it is within the judge’s discretion to invalidate all of a warden’s findings in a particular contest in the case of repeated low-quality submissions **

Link to verdict: **[[ COPY-PASTE LINK TO VERDICT]](https://docs.google.com/document/d/1Y2wJVt0d2URv8Pptmo7JqNd0DuPk_qF9EPJAj3iSQiE/edit#heading=h.2o4nijvduoow)**
