### ISSUE TITLE
Severity standardization - speculation on future code

### ISSUE THREAD

**Issue by trust1995** [code-423n4/org#72]
It would be beneficial for all of us to standardize severities for common issues, as we have seen variance among judges and contests.

Speculation on future code is a reason often used (Saw Alex use it frequently) to close submissions as out of scope. I agree in many cases this is a valid reason, for example when a future upgrade could make some part of the code not work, but it's unclear if that will ever happen.

There _are_ cases, though, where "speculation of future code" is an invalid way to close issues.

- Contracts which are meant to be inherited from, or composed with, that have unexpected behavior (breaking invariants). Even if no example of such use is in the project codebase.
- In centralization risk report, as a way to reject rugging vectors. 

Would be happy to hear more commentary and other cases where this reason doesn't hold, and when it does.

**Comment by dmvt** [comment]
In my view, this is valid if and only if the warden shows an example contract that would cause problems. Hand-wavy hypotheticals don't fly for me with these types of reports.

**Comment by dmvt** [comment]
I'll add to this. In a recent contest (I will link it after it is public), a class of contracts could have a feature in the future that one contract already has. Including this feature in any other contract of this type would cause the bug to exist. This is a valid example of future code speculation.

**Comment by Shungy** [comment]
I think there is a distinction between hypotheticals and actual code errors.

If code is correct and functions as intended for the current use, a finding speculating about a future potential upgrade that might create an exploitable scenario should be low risk. The reason is that with enough thinking, anyone can find a way where a future upgrade might create issues for any code.

If there is a mistake with the code, even if it does not cause issues in the current code, it should be medium. Those findings would always be appreciated by the sponsors and would be fixed. Such findings getting lost in QA and not getting fixed would be a shame. In the end, if a code is within the scope, and a warden spends the time and finds that error, they should be rewarded. For example, if it is a malfunction in a library function, others can use this library in their projects, or the sponsor project can be built further in a way that causes that function to cause serious harm.

**Comment by trust1995** [comment]
I understand your take @Shungy , but we also need to consider that C4 is a competitive platform, and it has the responsibility to award and incentivize wardens differentially. 
This is why we don't treat all mistakes as equal, but carefully judge their impact on system integrity and security.

**Comment by Shungy** [comment]
I agree. However C4 currently do not have sufficient granularity on severities. For example not all highs are equal. A critical exploit that can allow anyone to rug the protocol is High, and grouped with other Highs such as an erroneous function that can lead to loss to a user. The latter is almost always very limited in losses (e.g.: a user loses some money, devs find the issue and hide the function from UI until they fix the code and redeploy), while the former is a death sentence for the protocol.

So maybe there might be another solution than to consider mistakes that do not readily cause harm to the protocol as Medium. However, my problem in the example I gave is this: I provided value to the sponsor, which is evident by the sponsor fixing the issue. However, my payout from the finding was $0, and not only that, the finding was not even included in the report. So there is a disparity here between the value provided and value received. I do agree that making that finding Medium could be unfair to other wardens that have submitted Mediums with higher impact, but it is also unfair to just ignore the existence of that finding. Previously C4 had Low risks as separate category, maybe that is the solution.

**Comment by kartoonjoy** [comment]
Per the Autumn 2023 C4 Supreme Court verdicts, the Supreme Court's verdict on this issue is: 

> Any issue that is not exploitable within the scope of the contest is defined as speculating on future code. Any such speculation only has the potential to be valid if the root cause is demonstrated to be in the contest scope. Warden may make an argument on why a future code change that would make the bug manifest is reasonably likely. Based on likelihood considerations, the Judge may assign a severity rating in any way they see fit.
If the exploitability relies on a particular 3rd party integration, the likelihood must factor in a competent integrator who has done due diligence.


Link to verdict: https://docs.google.com/document/d/1Y2wJVt0d2URv8Pptmo7JqNd0DuPk_qF9EPJAj3iSQiE/edit#heading=h.mzj60e8gk7n1
